source 'https://rubygems.org'

gem 'sinatra', '~> 3.0'
gem 'dotenv'
gem 'mysql2', '~> 0.5.5'
gem 'sequel'
gem 'puma', '~> 6.4'
gem 'net-ping'
gem 'rufus-scheduler'
gem 'sinatra-strong-params', require: 'sinatra/strong-params'
gem 'byebug'
